version: '3.8'

services:
  web:
    image: ccr.ccs.tencentyun.com/library/nginx:latest
    container_name: neat-reader
    ports:
      - "8080:80"  # 将容器的 80 端口映射到主机的 8080 端口
    volumes:
      - ./:/usr/share/nginx/html  # 挂载项目目录，方便开发时实时更新
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # 挂载 nginx 配置
    restart: unless-stopped 